### ISSUE TITLE
configure file is in .gitignore

### ISSUE THREAD

**Issue by riemannzetagambit** [agordon/fastx_toolkit#10]
Shouldn't the actual configure file be included in the repo? It is currently in your .gitignore, so when I clone the repo there is no ./configure to do the build. If I download the .tar.bz2 directly from your site it includes the configure file. 

Your repo does include that configure.ac file, but I don't remember that be used for the initial build.

Thanks!

**Comment by agordon** [comment]
Hello @riemannzetagambit .

The answer is a resounding "no".
Sadly, this is a misconception perpetuated by github's broken system.

`configure` (and other build-related files, such as `Makefile.in`) are not supposed to be in the git repository. Putting them in it is incorrect, and is a misunderstanding of GNU-Autotools system.

When a package is ready to be released (e.g. when making a new stable version), the package maintainer (me in this case) runs `make dist` - this creates a `tar.gz` archive (or `tar.bz2` ,etc.), and that archive, often called a "tarball", contains all the required files for a simple build (simple meaning: run `./configure ; make ; sudo make install`).  This is generally meant for users who do not want to develop the code further, and just want to install the latest version from source code. 

When a package is cloned from its git repository, the implicit assumption is that the person who cloned it is a developer, or someone who is at least more familiar with the development process. In this case, the repository usually contains `configure.ac`, which is then used to 'bootstrap' the entire process.
In the typical case, there will be a `reconf` or `bootstrap` script, and if not (or even if there is), running `autoreconf -if` is usually sufficient. Running it will bootstrap the GNU-Autotools build files, and will create the expected `configure` file.

If you are familiar with python development, this is similar to running `python setup.py sdist` - it will create a tarball of the python package, with some additional important files which are not (and should not be) in the git repository.

Sadly, github's system offers a broken option: to download the git repository as a tarball (or zip file) - which on one hand does not contain the git repository metadata, and on the other hand does not contain the required supporting files. It might work OK for simple projects, or projects which do not use gnu autotools - but for autotools-baesd projects this is completely incorrect (and confuses many users).

For example, here's the GIT repository for gnu coreutils (mirrored on github):
    https://github.com/coreutils/coreutils
It contains `configure.ac`, and a `bootstrap` script. It does not contain `configure` script.
Whereas the official release tarballs do contain all the required files:
  http://ftp.gnu.org/gnu/coreutils/

(Note that the above applies for projects using gnu autotools as a build system. Project which use `makefile` directly, or CMake, or other build system might not require 'distribution' preparation steps - but the might have other issues).

I hope this answers the issue.
regards,
 gordon

**Comment by riemannzetagambit** [comment]
Thank you, Gordon. I am not a developer and was only looking for the 'simple' build. I think I also understand GNU-Autotools a bit better now.
