### ISSUE TITLE
compile-error on gcc 7

### ISSUE THREAD

**Issue by brobr** [agordon/fastx_toolkit#14]
Hi, fastx_toolkit  and llibgtextutils do no longer compile when using a recent compiler like GCC 7:

make[3]: Entering directory '/tmp/SBo/fastx_toolkit-0.0.14/src/fasta_formatter'
g++ -DHAVE_CONFIG_H -I. -I../..   -I/usr/local/include/gtextutils -I../../src/libfastx   -O2 -fPIC -Werror=implicit-fallthrough -Wall -Wextra -Wformat-nonliteral -Wformat-security -Wswitch-default -Wswitch-enum -Wunused-parameter -Wfloat-equal -Werror -DDEBUG -g -O1 -MT fasta_formatter.o -MD -MP -MF .deps/fasta_formatter.Tpo -c -o fasta_formatter.o fasta_formatter.cpp
fasta_formatter.cpp: In function ‘void parse_command_line(int, char**)’:
fasta_formatter.cpp:105:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
    usage();
    ~~~~~^~
fasta_formatter.cpp:107:3: note: here
   case 'i':
   ^~~~
cc1plus: all warnings being treated as errors
make[3]: *** [Makefile:425: fasta_formatter.o] Error 1
make[3]: Leaving directory '/tmp/SBo/fastx_toolkit-0.0.14/src/fasta_formatter'

**Comment by vflorelo** [comment]
Hi!
I just got the same issue. I'm no expert in C/C++ but this quick fix patched perfectly the problem
First, delete the function definition for usage, that is, remove these lines (90-94):
```
void print_usage()
{
	printf("%s",usage_string);
	exit(0);
}
```
Then, change this line (105, now 99), from this
```
			usage();
```
to this:
```
			printf("%s",usage_string);
			exit(0);
```
re-run make, and voila, all programs built properly

**Comment by brobr** [comment]
Fab! this translates to the attached patch-file "fastx-toolkit-gcc7-patch.txt". 
[fastx-toolkit-gcc7-patch.txt](https://github.com/agordon/fastx_toolkit/files/1182724/fastx-toolkit-gcc7-patch.txt)
Copy that file into the decompressed fastx_toolkit folder and then use this command to apply the patch:
 `patch  -p1 < fastx-toolkit-gcc7-patch.txt`
Then continue with compilation.
 
HTH
