### ISSUE TITLE
how to use  fastx_barcode_splitter.pl  to deal with  paired ends  fastq

### ISSUE THREAD

**Issue by werhoog** [agordon/fastx_toolkit#18]
Hi，I am very confused about  how to  use  fastx_barcode_splitter.pl  to deal with  paired ends  fastq.
For I have R1 and R1 two ends sequence fastq files and  fastx_barcode_splitter.pl  is seemed to deal with single end sequence fastq files.
what should I do?
Thanks !

**Comment by agordon** [comment]
Hello @werhoog,

 fastx_barcode_splitter.pl only works with single-end FASTQ files.
And specifically, it is (was?) needed only when using custom 5' barcoding.
If you use Illumina's native barcoding, there's really no need for this program any more.

regards,
gordon
