### ISSUE TITLE
Release 0.0.14 has a broken link

### ISSUE THREAD

**Issue by slowkow** [agordon/fastx_toolkit#4]
The link to download release 0.0.14 is broken:

https://github.com/agordon/fastx_toolkit/releases/download/0.0.14/fastx_toolkit-0.0.14.tar.bz2

Could you please provide binaries for Linux x86_64?

I cloned your repo, and successfully created a `configure` file, but it won't complete successfully quite yet. Could you provide any tips? Thanks!

``` bash
git clone https://github.com/agordon/fastx_toolkit.git
cd fastx_toolkit/
libtoolize --force
aclocal
autoheader 
automake --force-missing --add-missing
vim configure.ac 
automake --force-missing --add-missing
autoconf
autoreconf
automake --force-missing --add-missing
./configure --prefix=/home/unix/slowikow/.local/

./configure: line 14512: syntax error near unexpected token `GTEXTUTILS,gtextutils'
./configure: line 14512: `PKG_CHECK_MODULES(GTEXTUTILS,gtextutils)'
```

**Comment by ClaireMarchal** [comment]
Hi!

I've encountered the same error when trying to install this toolkit on a new computer. 
I've fixed this issue by copying the pkg.m4 file (for me in /usr/local/share/aclocal) in the cloned fastx_toolkit repository, and then, doing again the installation since the beginning.

Hope this could be helpfull.

Claire

**Comment by pseudogene** [comment]
Hi,

I got the same issue on a new distribution of Ubuntu. Make sure you have all necessary packages installed, specially `pkg-config`.
```
sudo apt-get install libtool automake autoconf pkg-config
git clone https://github.com/agordon/fastx_toolkit.git
cd fastx_toolkit
./reconf
./configure
make
```

Michaël
